test_anagram (__main__.TestExercice) ... FAIL
test_doubles (__main__.TestExercice) ... ok
test_grades (__main__.TestExercice) ... ERROR
test_histogram (__main__.TestExercice) ... FAIL
test_order (__main__.TestExercice) ... FAIL

======================================================================
ERROR: test_grades (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 63, in test_grades
    output = [exercice.best_grades(v) for v in values]
  File "test_exercice.py", line 63, in <listcomp>
    output = [exercice.best_grades(v) for v in values]
  File "/home/runner/work/c01_ch6_exercices-DavidPotvin-jpg/c01_ch6_exercices-DavidPotvin-jpg/exercice.py", line 32, in best_grades
    for student, notes in student_grades:
ValueError: too many values to unpack (expected 2)

======================================================================
FAIL: test_anagram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 40, in test_anagram
    'Erreur dans la vérification de l\'anagramme'
AssertionError: Lists differ: [False, False] != [True, False]

First differing element 0:
False
True

- [False, False]
+ [True, False] : Erreur dans la vérification de l'anagramme

======================================================================
FAIL: test_histogram (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 84, in test_histogram
    'Erreur dans les histogrammes'
AssertionError: [({}, []), ({}, [])] is not an instance of <class 'dict'> : First argument is not a dictionary

======================================================================
FAIL: test_order (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 25, in test_order
    'Mauvais ordre'
AssertionError: Lists differ: [False, False] != [[-2, 1, 6, 9], ['2', 'a', 'hello']]

First differing element 0:
False
[-2, 1, 6, 9]

- [False, False]
+ [[-2, 1, 6, 9], ['2', 'a', 'hello']] : Mauvais ordre

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3, errors=1)
